name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: calebjakemossey/ci-workflows/.github/workflows/python-ci.yaml@v1
    with:
      test-command: 'python -m pytest tests/'
      python-versions: '["3.10", "3.11", "3.12"]'
